### ISSUE TITLE
CONTOOL#6: deploy 'tools' host

### ISSUE THREAD

**Issue by joseosuna** [reddepruebas/tools#6]
# Details
**Story Points:** 1 point.

# Description
We need a host to deploy our website tools. It most be located in http://tools.reddepruebas.com.

**User:** Search engines, browsers.
**I Want:** when look at http://tools.reddepruebas.com the host is deployed.
**In order to:** display a host to website tools.

**Criteria:**
1. Write http://tools.reddepruebas.com and verify that website is deployed.

# Issue Links
**Blocks**
This issue *blocks*: 
[CONTOOL#3: add access control to connectionmonitoringtool website](https://github.com/reddepruebas/tools/issues/3)

This issue is *blocked* by: 
[CONTOOL#4: add website HTML meta tags](https://github.com/reddepruebas/tools/issues/4)

# Sub-Tasks
1. [x] [CONTOOL#15: Create a GAE Project for dashboard.](https://github.com/reddepruebas/tools/issues/15)
2. [x] [CONTOOL#16: Clone GitHub code.](https://github.com/reddepruebas/tools/issues/16)
3. [x] [CONTOOL#17: Deploy code on GAE server.](https://github.com/reddepruebas/tools/issues/17)

# Time Tracking
**Date Started:** May 13, 2015.
**Time Spent:** *(eg. 3w 4d 12h)* 2h 30m.
